### ISSUE TITLE
Unable to see "login with google" after install

### ISSUE THREAD

**Issue by jobartucz** [mantisbt-plugins/GoogleOauth#21]
Hi there, I followed the directions in the readme, put in my Authorized Javascript origin, Authorized redirect URI, GoogleAPI Client ID, and GoogleAPI Client Secret. Everything saved and looks good. 

When I log out, I don't see anything on the login page that wasn't there before. Do I need to add something manually?

Thanks,
JB

**Comment by PennStaterr** [comment]
I did have it working, but am now experiencing the same issue as you. The Google signin button has disappeared from the login page. Is it possible that Google changed something and an update to this plugin is needed?

**Comment by EmPo79** [comment]
We have the same problem, there are someone that could help us to solve the problem.

Thank you

**Comment by simonrenger** [comment]
check your server settings. In my case the butten was gone because of a 430 error

**Comment by jobartucz** [comment]
What did you do to solve it?

**Comment by simonrenger** [comment]
@jobartucz

I had the following error in my log file:

```
AH01630: client denied by server configuration: /var/www/vhosts/.../plugins/GoogleOauth/pages/assets/js/plugin.js, referer: https://.../login_page.php
```

I solved this by  adding to my apache config:

```
<Location /plugins/GoogleOauth>
	Require all granted
</Location>
```
